# ----
# Site

title: CloudCannon Documentation
display_title: Documentation
url: "https://docs.cloudcannon.com"
baseurl:
google_analytics_key: UA-37472773-1
show_full_navigation: false
theme: jekyll-theme-cloudcannon

active_sibling: Documentation
main_url: https://cloudcannon.com

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentation for CloudCannon, the Cloud CMS for Jekyll.
social:
  name: CloudCannon
  links:
    - https://www.facebook.com/CloudCannon
    - https://twitter.com/CloudCannon
    - https://plus.google.com/+CloudCannon
    - https://www.youtube.com/c/CloudCannon
twitter:
  username: CloudCannon

# -----
# Build

permalink: pretty

plugins:
  - jekyll-data
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

exclude:
  - Gemfile
  - Gemfile.lock

collections_dir: collections
collections:
  project_docs:
    title: Projects
    permalink: /projects/:path/
    output: true
    boost: 8
  sharing_docs:
    title: Sharing
    permalink: /sharing/:path/
    output: true
    boost: 8
  build_docs:
    title: Builds
    permalink: /builds/:path/
    output: true
    boost: 8
  editing_docs:
    title: Editing
    permalink: /editing/:path/
    output: true
    boost: 8
  file_docs:
    title: Files
    permalink: /files/:path/
    output: true
    boost: 8
  hosting_docs:
    title: Hosting
    permalink: /hosting/:path/
    output: true
    boost: 8
  organisation_docs:
    title: Organisations
    permalink: /organisations/:path/
    output: true
    boost: 8
  i18n_docs:
    title: Internationalisation
    permalink: /i18n/:path/
    output: true
    boost: 8
  sections:
    title: Sections
    permalink: /:path/
    output: false
  editable_regions:
    title: Editable Regions
    output: false
  inputs:
    title: Inputs
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      hide_cta: true
      layout: doc
      search_result_highlighting_selector: article.content
      _options:
        content:
          format: p h2 h3
          bold: true
          link: true
          italic: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          outdent: true
          indent: true
          image: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      search_result_highlighting_selector: div.post
      hide_disqus: true
      _comments:
        type: Marks the impact of this release
      _options:
        content:
          format: p h2 h3
          bold: true
          link: true
          italic: true
          removeformat: true
          numberedlist: true
          bulletedlist: true
          code: true
          table: true
          outdent: true
          indent: true
          image: true

# -----------
# CloudCannon

types:
  - minor
  - major

builds:
  - Any
  - Static
  - Jekyll

plans:
  - Free
  - Basic
  - Pro

hostings:
  - Any
  - CloudCannon
